package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GB2312\">\r\n");
      out.write("<title>Bootstrap, from Twitter</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- Le styles -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\" ccnx://bupt/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\" ccnx://bupt/css/inettuts.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\" ccnx://bupt/css/inettuts.js.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("\t/* 60px to make the container go all the way to the bottom of the topbar */\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* add by me */\r\n");
      out.write("#columns #column1 {\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#columns #column3 {\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#columns .widget .widget-head {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("}\r\n");
      out.write(".uneditable-input {\r\n");
      out.write("  height: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\" ccnx://bupt/css/bootstrap-responsive.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Le fav and touch icons -->\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("\thref=\" ccnx://bupt/ico/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\r\n");
      out.write("\thref=\" ccnx://bupt/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\"\r\n");
      out.write("\thref=\" ccnx://bupt/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\"\r\n");
      out.write("\thref=\" ccnx://bupt/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("\thref=\" ccnx://bupt/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\t\t<a class=\"brand\" href=\"/\" title=\"记忆犹新\" style=\"padding-left: 28px;\">\r\n");
      out.write("\t\t\t\t\tNext Network</a>\r\n");
      out.write("\t\t\t\t<ul id=\"navigation\" class=\"nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\" ccnx://bupt//category/memory\">首页</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\" ccnx://bupt//category/lover\">测试1</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\" ccnx://bupt//category/travel\">测试2</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\" ccnx://bupt//category/flavor\">测试3</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\" ccnx://bupt//category/timeline\">测试4</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-pills pull-right\" style=\"padding-right: 30px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#loginModal\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"modal\"> <i class=\"icon-user icon-white\"></i>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<span style=\"color:white\">登录/注册</span> <!--\r\n");
      out.write("                            <a class=\"pull-right\" href=\"/auth/register\">注册</a>\r\n");
      out.write("                            <a class=\"pull-right\" href=\"/auth/signin\">登录</a>\r\n");
      out.write("                            --> </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div id=\"loginModal\" class=\"modal hide fade login-modal\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("\t\t\t\t<h3>请先登录</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<h4>使用微博账号登录</h4>\r\n");
      out.write("\t\t\t\t<p>更好的收藏和分享，并发现好友的推荐！</p>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"display:inline-block; margin-left: 3px\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-large btn-danger dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" style=\"padding: 6px 14px\">\r\n");
      out.write("\t\t\t\t\t\t\t微博登录&nbsp;<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"share\" class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"rec-sina\"><a href=\"/user/sina/oauth\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-size: 12px;\"> 新浪微博 </a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr style=\"size: 2px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"login-form\" action=\"ccnx://bupt/servlet/LoginServlet\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<h4>使用本站账号登录</h4>\r\n");
      out.write("\t\t\t\t\t\t<p></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">邮箱<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input class=\"span3\" size=\"16\" name=\"LoginForm_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"LoginForm_email\" type=\"text\"> <span><div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"errorMessage\" id=\"LoginForm_email_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">密码<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-asterisk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input class=\"span3\" size=\"16\" name=\"LoginForm_password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"LoginForm_password\" type=\"password\"> <span><div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"errorMessage\" id=\"LoginForm_password_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox login-checkbox\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"LoginForm_checkbox\" class=\"login-checkbox\" type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t下次自动登录（一周） </label>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-info span2\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\" ccnx://bupt/login.jsp\" class=\"btn span2\">注册</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"span5 offset1 well\" style=\"height: 360px\">\r\n");
      out.write("\t\t\t\t<h3>快速注册账号</h3>\r\n");
      out.write("\t\t\t\t<hr style=\"size: 2px\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"register-form\" action=\"ccnx://bupt/servlet/RegisterServlet\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">邮箱<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input size=\"16\" name=\"RegisterForm_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"RegisterForm_email\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"errorMessage\" id=\"RegisterForm_email_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">昵称<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input placeholder=\"(4-12位，中英文或数字)\" size=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"RegisterForm_nickname\" id=\"RegisterForm_nickname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" maxlength=\"12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"errorMessage\" id=\"RegisterForm_nickname_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">密码<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-asterisk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input placeholder=\"(4-16位)\" size=\"16\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"RegisterForm_password\" id=\"RegisterForm_password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"password\" maxlength=\"16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"errorMessage\" id=\"RegisterForm_password_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">再次输入密码<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-asterisk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input size=\"16\" name=\"RegisterForm_password_confirmation\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"RegisterForm_password_confirmation\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaxlength=\"16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"errorMessage\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"RegisterForm_password_confirmation_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-actions login-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-info span2\">立即注册</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"span5 well\" style=\"height: 360px\">\r\n");
      out.write("\t\t\t\t<h3>使用微博账号登录</h3>\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"display:inline-block; margin-left: 3px\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-large btn-danger dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" style=\"padding: 6px 14px\">\r\n");
      out.write("\t\t\t\t\t\t\t微博登录&nbsp;<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"share\" class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"rec-sina\"><a href=\"/user/sina/oauth\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-size: 12px;\"> 新浪微博 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--                <li class=\"rec-tx\">-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--                    <a href=\"-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--\" style=\"font-size: 12px;\">-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--                        腾讯微博-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--                    </a>-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--                </li>-->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"size: 2px\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" id=\"login-form\" action=\"ccnx://bupt/servlet/LoginServlet\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<h3>使用本站账号登录</h3>\r\n");
      out.write("\t\t\t\t\t\t<!--  <h4>\r\n");
      out.write("                {{error}}\r\n");
      out.write("            </h4> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">邮箱<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input class=\"span3\" size=\"16\" name=\"LoginForm_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"LoginForm_email\" type=\"text\"> <span><div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"errorMessage\" id=\"LoginForm_email_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\">密码<font\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red\">*</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-asterisk\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <input class=\"span3\" size=\"16\" name=\"LoginForm_password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"LoginForm_password\" type=\"password\"> <span><div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"errorMessage\" id=\"LoginForm_password_em_\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label login\"></label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox login-checkbox\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"LoginForm_checkbox\" class=\"login-checkbox\" type=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t下次自动登录（一周） </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-actions login-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-info span2\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"errorwarning\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\" ccnx://bupt/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\" ccnx://bupt/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\" ccnx://bupt/js/jquery-ui-personalized-1.6rc2.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\" ccnx://bupt/js/inettuts.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("    var errorwarning = $(\"#errorwarning\").attr(\"title\");\r\n");
      out.write("    if(errorwarning!=\"\"&&errorwarning!=null){\r\n");
      out.write("        alert(errorwarning);\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
